# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_libs_mvc', '0002_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='test',
            field=models.IntegerField(default=0),
        ),
    ]
