# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_libs_mvc', '0003_choice_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='test',
        ),
    ]
