# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 16:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sweet_libs_mvc', '0004_remove_choice_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_name',
        ),
        migrations.AddField(
            model_name='choice',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='name', max_length=200),
        ),
    ]
